import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import api from '@/lib/api'
import { TrendingUp, Plus, Search, Tag } from 'lucide-react'

const CATEGORIES = [
  'مبيعات عامة', 'استثمار', 'تمويل', 'عمولة', 'إيرادات أخرى'
]

export default function IncomesPage() {
  const queryClient = useQueryClient()
  const [search, setSearch] = useState('')
  const [showAdd, setShowAdd] = useState(false)
  const [form, setForm] = useState({ title: '', amount: '', category: 'مبيعات عامة', date: new Date().toISOString().split('T')[0], notes: '', project_id: '' })

  const { data: projectsData } = useQuery({
    queryKey: ['projects-list'],
    queryFn: () => api.get('/projects?per_page=100').then(r => r.data),
  })

  const { data, isLoading } = useQuery({
    queryKey: ['incomes', search],
    queryFn: () =>
      api.get('/incomes', { params: { per_page: 50, search: search || undefined } }).then(r => r.data),
  })

  const { data: invoicesData, isLoading: loadingInvoices } = useQuery({
    queryKey: ['invoices-for-incomes'],
    queryFn: () => api.get('/invoices', { params: { per_page: 200 } }).then(r => r.data),
  })

  const addMutation = useMutation({
    mutationFn: (data: any) => api.post('/incomes', data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['incomes'] })
      setShowAdd(false)
      setForm({ title: '', amount: '', category: 'مبيعات عامة', date: new Date().toISOString().split('T')[0], notes: '', project_id: '' })
    },
  })

  const manualIncomes = data?.data ?? []
  
  // Merge with paid invoices
  const invoices = invoicesData?.data ?? []
  const paidInvoices = invoices.filter((inv: any) => inv.status === 'paid' || (inv.status === 'partially_paid' && inv.total - (inv.remaining_amount || inv.total) > 0))
  
  const mappedInvoices = paidInvoices.map((inv: any) => {
    const paidAmount = inv.status === 'paid' ? Number(inv.total) : Number(inv.total) - Number(inv.remaining_amount || inv.total)
    return {
      id: `inv-${inv.id}`,
      title: `فاتورة محصلة: ${inv.invoice_number}`,
      category: 'إيراد فواتير',
      amount: paidAmount,
      date: inv.issue_date || inv.created_at,
      project: inv.project,
      notes: 'تم التسجيل تلقائياً من الفواتير المدفوعة',
      isAutoGenerated: true
    }
  })

  const allIncomes = [...manualIncomes, ...mappedInvoices]
    .filter(inc => !search || inc.title.toLowerCase().includes(search.toLowerCase()))
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())

  const byCategory = allIncomes.reduce((acc: Record<string, number>, e: any) => {
    acc[e.category] = (acc[e.category] || 0) + Number(e.amount)
    return acc
  }, {})

  const totalThisMonth = allIncomes
    .filter((e: any) => {
      const d = new Date(e.date)
      const now = new Date()
      return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear()
    })
    .reduce((s: number, e: any) => s + Number(e.amount), 0)

  const isDataLoading = isLoading || loadingInvoices

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h2 className="text-xl font-bold text-[hsl(var(--foreground))]">الإيرادات المستقلة</h2>
          <p className="text-sm text-[hsl(var(--muted))]">
            هذا الشهر: <strong className="text-emerald-500">{totalThisMonth.toLocaleString('ar-AE')} د.إ</strong>
          </p>
        </div>
        <button className="btn-primary bg-emerald-600 hover:bg-emerald-700 text-white" onClick={() => setShowAdd(!showAdd)}>
          <Plus size={16} /> إضافة إيراد
        </button>
      </div>

      {/* Quick Add Form */}
      {showAdd && (
        <div className="glass-card p-5 border-s-4 border-emerald-400">
          <h3 className="font-semibold mb-4 text-[hsl(var(--foreground))] text-emerald-600">إضافة إيراد جديد</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-3">
            <input placeholder="العنوان (مثال: أرباح استثمار)" value={form.title}
              onChange={e => setForm({...form, title: e.target.value})} className="form-input" />
            <input type="number" placeholder="المبلغ (د.إ)" value={form.amount}
              onChange={e => setForm({...form, amount: e.target.value})} className="form-input" />
            <select value={form.category} onChange={e => setForm({...form, category: e.target.value})} className="form-input">
              {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
            </select>
            <input type="date" value={form.date}
              onChange={e => setForm({...form, date: e.target.value})} className="form-input" />
            <select value={form.project_id} onChange={e => setForm({...form, project_id: e.target.value})} className="form-input">
              <option value="">بدون مشروع</option>
              {projectsData?.data?.map((p: any) => <option key={p.id} value={p.id}>{p.name}</option>)}
            </select>
            <input placeholder="ملاحظات (اختياري)" value={form.notes}
              onChange={e => setForm({...form, notes: e.target.value})} className="form-input" />
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => addMutation.mutate({ ...form, project_id: form.project_id || null })}
              disabled={!form.title || !form.amount || addMutation.isPending}
              className="btn-primary bg-emerald-600 hover:bg-emerald-700"
            >
              {addMutation.isPending ? 'جارٍ الحفظ...' : 'حفظ الإيراد'}
            </button>
            <button onClick={() => setShowAdd(false)} className="btn-secondary">إلغاء</button>
          </div>
        </div>
      )}

      {/* Category Summary */}
      {Object.keys(byCategory).length > 0 && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {Object.entries(byCategory).slice(0, 4).map(([cat, val]) => (
            <div key={cat} className="glass-card p-3">
              <div className="flex items-center gap-1.5 mb-1">
                <Tag size={12} className="text-emerald-500" />
                <span className="text-xs text-[hsl(var(--muted))]">{cat}</span>
              </div>
              <div className="font-bold text-[hsl(var(--foreground))] text-emerald-600">{(val as number).toLocaleString('ar-AE')} <span className="text-xs font-normal text-[hsl(var(--muted))]">د.إ</span></div>
            </div>
          ))}
        </div>
      )}

      <div className="relative max-w-sm">
        <Search size={15} className="absolute top-1/2 -translate-y-1/2 start-3 text-[hsl(var(--muted))]" />
        <input type="text" placeholder="البحث..." value={search}
          onChange={e => setSearch(e.target.value)} className="form-input ps-9 h-9 py-2" />
      </div>

      <div className="glass-card overflow-hidden">
        {isDataLoading ? (
          <div className="space-y-2 p-4">
            {[...Array(5)].map((_, i) => <div key={i} className="h-12 bg-[hsl(var(--border))] animate-pulse rounded-lg" />)}
          </div>
        ) : (
          <table className="w-full data-table">
            <thead>
              <tr>
                <th className="text-start">العنوان</th>
                <th className="text-start">المشروع</th>
                <th className="text-start">الفئة</th>
                <th className="text-start">التاريخ</th>
                <th className="text-start">المبلغ</th>
                <th className="text-start">ملاحظات</th>
              </tr>
            </thead>
            <tbody>
              {allIncomes.map((e: any) => (
                <tr key={e.id} className={e.isAutoGenerated ? 'bg-emerald-50/30 dark:bg-emerald-900/10' : ''}>
                  <td className="font-medium text-sm">
                    {e.title}
                    {e.isAutoGenerated && <span className="ml-2 text-[10px] bg-emerald-100 text-emerald-700 px-1.5 py-0.5 rounded-full dark:bg-emerald-900/50 dark:text-emerald-300">تلقائي</span>}
                  </td>
                  <td className="text-xs font-medium text-emerald-600">{e.project?.name || '—'}</td>
                  <td>
                    <span className="badge-gray text-xs px-2 py-0.5 rounded-full">{e.category}</span>
                  </td>
                  <td className="text-xs text-[hsl(var(--muted))]">
                    {e.date ? new Date(e.date).toLocaleDateString('ar-AE') : '—'}
                  </td>
                  <td className="font-semibold text-emerald-600 text-sm">
                    {Number(e.amount).toLocaleString('ar-AE')} <span className="text-xs font-normal text-[hsl(var(--muted))]">د.إ</span>
                  </td>
                  <td className="text-xs text-[hsl(var(--muted))] max-w-48 truncate">{e.notes ?? '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
        {!isDataLoading && allIncomes.length === 0 && (
          <div className="text-center py-12 text-[hsl(var(--muted))]">
            <TrendingUp size={36} className="mx-auto mb-2 text-emerald-500 opacity-30" />
            لا توجد إيرادات مسجّلة
          </div>
        )}
      </div>
    </div>
  )
}
